# Generated by Django 3.1.4 on 2020-12-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_DB', '0003_auto_20201214_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tag',
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='RMS_DB.Tag'),
        ),
    ]
