# Generated by Django 3.1.4 on 2020-12-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_DB', '0004_auto_20201214_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
