# Generated by Django 3.1.4 on 2020-12-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_DB', '0005_auto_20201214_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered')], max_length=200, null=True),
        ),
    ]
