# Generated by Django 3.1.4 on 2020-12-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_DB', '0006_auto_20201214_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
