# Generated by Django 3.1.4 on 2020-12-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_DB', '0007_auto_20201216_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Out Door', 'Out Door')], max_length=200, null=True),
        ),
    ]
