# Generated by Django 3.1.4 on 2020-12-17 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS_DB', '0008_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RMS_DB.tag'),
        ),
    ]
